[package]
name = "surrealmcp"
version = "0.5.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive", "env"] }
rmcp = { version = "0.6.0", features = ["server", "macros"] }
rustls = "0.23.31"
schemars = "1.0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
surrealdb = { version = "3.0.5", features = ["protocol-ws", "rustls"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
